openapi: 3.2.0
info:
  title: OpenGov Enterprise Asset Management Commands API
  version: 1.0.0
  description: 'OpenGov Enterprise Asset Management API

    '
  contact:
    name: OpenGov Enterprise Asset Management API
    url: developers@opengov.com
  license:
    name: OpenGov Enterprise Asset Management API
    url: https://opengov.com
servers:
- url: '{serverURL}'
  description: Your EAM Server Instance
tags:
- name: Commands
paths:
  /api/v1/commands/scenarios/runscenarioasync/jobs/{JobId}:
    get:
      $ref: components/Commands/Scenarios/getScenarioJob.yaml#/get
      tags:
      - Commands
    delete:
      $ref: components/Commands/Scenarios/cancelScenarioJob.yaml#/delete
      tags:
      - Commands
x-tagGroups:
- name: Authentication
  tags:
  - Authentication
- name: User
  tags:
  - User
- name: Discover
  tags:
  - Discover
- name: Metadata
  tags:
  - Meta/Classes
  - Meta/TargetedLists
- name: Business Objects
  tags:
  - BusinessObjects/Create
  - BusinessObjects/Read
  - BusinessObjects/Update
  - BusinessObjects/Delete
- name: Attachments
  tags:
  - Attachments/Create
  - Attachments/Read
  - Attachments/Delete
- name: Security
  tags:
  - Security
- name: Layout
  tags:
  - Layout
- name: Commands
  tags:
  - Commands/ScenarioCommands
  - Commands/AssetCommands
- name: Files
  tags:
  - Files
- name: Structure
  tags:
  - Structure
